name: Python Lint & Style Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint
          pip install -r requirements.txt
      - name: Run flake8 (code style)
        run: |
          flake8 labs/ tools/ main.py
      - name: Run pylint (broken references)
        run: |
          pylint labs/ tools/ main.py --rcfile=.pylintrc --disable=missing-docstring,invalid-name,too-few-public-methods
